### PR TITLE
Encrypting Email Address in commit message.

### PR DESCRIPTION
**Pull request by jwendl**
This is just a PR to consider encrypting the email address in the yaml that gets committed to the repository. 

We could one way hash it as well like we do with gravatar, but if you are a blog owner - it might be nice to know what email someone provided in the event you'd wish to contact them. So using RSA public key private key can help with that as you can hold on to the private key and decrypt the value as needed. 

Mainly an issue because on the comment form we say we don't ever show it, yet GitHub does :smile:
Before: https://github.com/jwendl/jwendl.github.io/pull/28/files

After: https://github.com/jwendl/jwendl.github.io/pull/40/files

### CODE REVIEW

**Comment by damieng** [comment]
My blog source and comments are a private repo so I didn't give this as much thought as I should.

@Haacked has suggested that we drop email and gravatar entirely and just have 'avatarUrl' that points to an image.  This would allow for other imports/exports that don't have emails while still retaining some kind of visual identity.

Would that work for you too @jwendl ?

**Comment by jwendl** [comment]
Could work, would the email still be on the form though so it generates the gravatar link? Not sure about how many folks come to a site to leave a comment while knowing their gravatar link.

**Comment by Haacked** [comment]
Yeah, the email address would still be on the form. In fact, we probably _don't_ want to accept avatar URL because...well...the internet.

Damien and I talked about making that form field configurable with a dropdown. For example, it could be an option field where you could either put your gravatar email, or your github handle, and we'd obtain the avatar on the server side and render the avatar in the comment PR so that you can review it (because even a gravatar can be just awful).

That would open the door to supporting other options such as Twitter, Facebook, etc.

**Comment by damieng** [comment]
I like the concept although following the redirect means that their GitHub avatar would be locked in time right?  Can't we just store their GitHub name and disclose what it's doing on the submit form?

Then we could just call it avatarID.  I'd also like to extend this to Twitter which uses https://twitter.com/{twitter-handle}/profile_image?size=original etc.

**Comment by Haacked** [comment]
> Can't we just store their GitHub name and disclose what it's doing on the submit form?

The problem is that creates a lot of work for the clients.

For example, if you make a request for `https://github.com/haacked.png?s=64`, GitHub ignores the `?s=64` parameter and redirects to the full size avatar: `https://avatars1.githubusercontent.com/u/19977?v=4`

So in order to support GitHub, a client would have to make that request, follow the redirect, then append the size querystring parameter. I could probably ping folks at GitHub to see if we can just fix that.

The other option is to just not support GitHub for now and support Twitter and Gravatar.

**Comment by Haacked** [comment]
If we supported GitHub, my proposal was to follow the redirect when a user submits a form and parse out the user id and store _that_ as the `avatarId`. We wouldn't store the full URL.

I think if you make a request to `https://avatars1.githubusercontent.com/u/{userid}` you get the latest version.

**Comment by damieng** [comment]
Can't we just store the unique id and what platform it was for?

e.g.
- `twitter,@damienguard`
- `gravatar,dc72963e7279d34c85ed4c0b731ce5a9`
- `github,damieng`
- `email,damieng@gmail.com`

And then leave it up to client side code as to determine what should be sent in those two fields and which they want to accept?  m5 is easy in browser.

**Comment by Haacked** [comment]
> Can't we just store the unique id and what platform it was for?

That would make supporting GitHub really difficult on the client. But doable. Yeah, I suppose we could put more of the work on the client. Keeps things simple and predictable.

**Comment by damieng** [comment]
No activity.

**Pull request closed without merging**
